# Generated by Django 5.1.2 on 2024-11-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_remove_company_id_admin_user_company_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplications',
            fields=[
                ('Internship_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to='home.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('job_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='home.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='home.student')),
            ],
        ),
    ]
