# Generated by Django 5.1.2 on 2024-11-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_job_company_remove_job_created_by_internships_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipapplications',
            old_name='Internship_application_id',
            new_name='internship_application_id',
        ),
        migrations.RenameField(
            model_name='internships',
            old_name='Internship_id',
            new_name='internship_id',
        ),
        migrations.RenameField(
            model_name='internships',
            old_name='Internship_role',
            new_name='internship_role',
        ),
        migrations.RenameField(
            model_name='internships',
            old_name='Internship_type',
            new_name='internship_type',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Job_type',
            new_name='job_type',
        ),
    ]
