# Generated by Django 5.1.2 on 2024-11-07 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_internship_application_id_internshipapplications_internship_application_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='company',
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('internship_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('internship_role', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('internship_type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=20)),
                ('location', models.CharField(choices=[('remote', 'Remote'), ('in_office', 'In Office'), ('hybrid', 'Hybrid')], max_length=20)),
                ('stipend', models.IntegerField()),
                ('start_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('last_date_to_apply', models.DateField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='home.company')),
            ],
        ),
        migrations.AlterField(
            model_name='internshipapplications',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to='home.internship'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=20)),
                ('location', models.CharField(choices=[('remote', 'Remote'), ('in_office', 'In Office'), ('hybrid', 'Hybrid')], max_length=20)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('last_date_to_apply', models.DateField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='home.company')),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='home.job'),
        ),
        migrations.DeleteModel(
            name='Internships',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
