# Generated by Django 5.1.2 on 2024-11-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_internshipapplications_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
